name: Basic Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Werkzeug==2.0.3
          pip install Flask==2.0.1
          pip install requests==2.26.0
          pip install python-dotenv==0.19.0
          
      - name: Test imports
        run: |
          python -c "import werkzeug; import flask; import requests; print('All imports successful!')"
